export interface PrescriptionItem {
    _id?: string,
    productName?: string,
    productId?: string,
    genericName: string,
    ingredients?: any[],
    form?: string,
    frequency: string,
    duration: string,
    cost?: number,
    totalCost?: number,
    routeName: String,
    quantity?: number,
    patientInstruction: string,
    isRefill?: Boolean,
    isExternal: Boolean,
    refillCount: number,
    initiateBill: boolean,
    isBilled: boolean,
    isOpen?: boolean,
    transactions?: any[],
    serviceId?: string,
    facilityServiceId?: string
}